### ISSUE TITLE
Opti: remove double iszero before jumpi

### ISSUE THREAD

**Issue by obatirou** [huff-language/huffmate#117]
## Overview
There are several contracts where there are two `iszero` in a row before a `jumpi` to conditionally jump if a value is different from 0. But those are not necessary in certain contexts.
From [evm.codes](https://www.evm.codes/):
>b:  the program counter will be altered with the new value only if this value is different from 0. Otherwise, the program counter is simply incremented and the next instruction will be executed.

For example, in case of a `call` (delegate, static, or classic), they return `success`:
> success: return 0 if the sub [context](https://www.evm.codes/about) [reverted](https://www.evm.codes/#FD), 1 otherwise.

So, if there is a `jumpi` just after a call, there is no need to do `iszero iszero`.
Using the `success` directly from the stack is sufficient.
Removing those double `iszero` could save 2 instructions each times those macros are called.

## Todo
Contracts where there are possible improvements:
- [ ] ERC4626 (see [PR](https://github.com/huff-language/huffmate/pull/116))
- [ ] ERC1967Upgrade
- [ ] ERC20_TRANSFER (utils)
- [ ] SSTORE2_WRITE (after a `create` but same principle applies)
- [ ] ERC721 (check if an address is != address(0))

**Comment by Raybolt-wen** [comment]
This seems solve. Think we can close.
